version: "3"
services:
  mssql:
    image: "microsoft/mssql-server-linux:2017-CU12"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=eioC9vvCZzQSy4S9g37i
    ports:
      - "1433:1433"
  mysql:
    image: "mysql:5"
    environment:
      - MYSQL_DATABASE=db_errors_test
      - MYSQL_USER=db_errors
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
  postgres:
    image: "postgres:10"
    environment:
      - POSTGRES_DB=db_errors_test
      - POSTGRES_USER=db_errors
      - POSTGRES_PASSWORD=db_errors_password
    ports:
      - "5432:5432"
